export default {
  HOME: 'Home',
  LOGIN_SCREEN: 'LoginScreen',
  SIGN_UP_SCREEN: 'SignUpScreen',
  SUCCESSFULLY_CREATE_ACCOUNT: 'SuccessfullyCreateAccountScreen',
  FORGOT_PASSWORD: 'ForgotPasswordScreen',
  PHOTO_CAPTURE_SCREEN: 'PhotoCaptureScreen',
  CREATE_POST_SCREEN: 'CreatePostScreen',
  CREATE_STORY_SCREEN: 'CreateStoryScreen',
  SHOW_GALLERY_STORY: 'ShowGalleryStoryScreen',
  EDIT_PROFILE: 'EditProfileScreen',
  SETTING_SCREEN: 'SettingScreen',
  SHOW_ALL_USER_POSTS: 'ShowAllUserPostsScreen',
  USER_PROFILE: 'UserProfileScreen',
  FOLLOWER_FOLLOWING_SCREEN: 'FollowerAndFollowingScreen',
  EDIT_POST_SCREEN: 'EditPostScreen',
  ABOUT_ACCOUNT_SCREEN: 'AboutAccountScreen',
  SAVED_POSTS_SCREEN: 'SavedPostsScreen',
  DISCOVER_PEOPLE_SCREEN: 'DiscoverPeopleScreen',
  NOTIFICATION_SCREEN: 'NotificationScreen',
  SHOW_GALLERY_REEL: 'ShowGalleryReelScreen',
  CREATE_REEL_SCREEN: 'CreateReelScreen',
  CHAT_SCREEN: 'ChatScreen',
  SEARCH_PEOPLE_SCREEN: 'SearchPeopleScreen',
  EXPLORE_SCREEN: 'ExploreScreen',
  CHAT_USERS_LIST_SCREEN: 'ChatUsersListScreen',
  CHAT_SEARCH_SCREEN: 'ChatSearchScreen',
};
